name: dagger
on:
  push:
    branches: "**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dagger/dagger-for-github@v5
        with:
          verb: call
          module: .
          args: --env GHA --dir . ci
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}